apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app: tgsaver

secretGenerator:
- name: tgsaver
  envs:
  - env

bases:
- ../../base

images:
- name: iaroki/tgsaver
  newTag: "1.0"
